export const reviews = [
  {
    id: 1,
    name: 'Maria Rossi',
    role: 'Visitatrice',
    rating: 5,
    text: "Un'esperienza incredibile! La processione in mare è stata emozionante, i fuochi d'artificio spettacolari. Termoli durante San Basso è magica!",
    image: 'https://i.pravatar.cc/150?img=5',
    lang: 'it',
  },
  {
    id: 2,
    name: 'John Smith',
    role: 'Tourist',
    rating: 5,
    text: "Amazing festival! The maritime procession was breathtaking. The atmosphere in the old town was absolutely magical. Can't wait to come back!",
    image: 'https://i.pravatar.cc/150?img=12',
    lang: 'en',
  },
  {
    id: 3,
    name: 'Giuseppe Lombardi',
    role: 'Famiglia',
    rating: 5,
    text: "Siamo venuti con i bambini e si sono divertiti moltissimo. L'atmosfera festosa, il cibo delizioso e la gente accogliente. Torneremo sicuramente!",
    image: 'https://i.pravatar.cc/150?img=33',
    lang: 'it',
  },
  {
    id: 4,
    name: 'Sophie Dubois',
    role: 'Touriste',
    rating: 4,
    text: "Magnifique célébration! La procession en mer était spectaculaire. J'ai adoré l'authenticité de cette fête traditionnelle. Termoli est une perle!",
    image: 'https://i.pravatar.cc/150?img=9',
    lang: 'fr',
  },
  {
    id: 5,
    name: 'Antonio Greco',
    role: 'Coppia',
    rating: 5,
    text: 'Romantico e suggestivo. La sera della processione abbiamo cenato sul lungomare, esperienza indimenticabile. Consigliato a tutti!',
    image: 'https://i.pravatar.cc/150?img=14',
    lang: 'it',
  },
  {
    id: 6,
    name: 'Laura Bianchi',
    role: 'Residente',
    rating: 5,
    text: 'Vivo a Termoli da sempre e ogni anno San Basso mi emoziona. È il nostro orgoglio, la nostra tradizione. Venite a viverla con noi!',
    image: 'https://i.pravatar.cc/150?img=45',
    lang: 'it',
  },
  {
    id: 7,
    name: 'Marco Ferrari',
    role: 'Fotografo',
    rating: 5,
    text: 'Come fotografo ho trovato scene incredibili. La luce sul mare durante la processione, i volti dei fedeli, i fuochi... pura magia!',
    image: 'https://i.pravatar.cc/150?img=52',
    lang: 'it',
  },
  {
    id: 8,
    name: 'Emma Wagner',
    role: 'Traveler',
    rating: 4,
    text: 'Such an authentic Italian experience! The devotion of the locals, the beautiful rituals, and the fireworks over the sea were unforgettable.',
    image: 'https://i.pravatar.cc/150?img=23',
    lang: 'en',
  },
];
